# This is a basic workflow to help you get started with Actions

name: default
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Compile and extract the artifact from docker container
      run: |
        mkdir -p dist
        docker build -t alpine:proot -f Dockerfile.alpine .
        docker run --rm -v $(pwd):/workdir alpine:proot cp /proot/dist/proot /workdir/dist/proot

    - name: Set permissions for dist directory
      run: |
        sudo chown -R "$(id -u)":"$(id -g)" dist/
        sudo chmod -R 766 dist/

    - name: Upload artifact to release
      uses: actions/upload-artifact@v1.0.0
      with:
        name: proot
        path: 'dist'

    - name: Compute Short SHA
      id: ssha
      run: |
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    outputs:
      git_ssha: ${{ steps.ssha.outputs.sha_short }}


  release:
      permissions: write-all
      needs: [build]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v1
          with:
            name: proot

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: Continuous ${{ needs.build.outputs.sha_short }}
            automatic_release_tag: ${{ needs.build.outputs.sha_short }}
            prerelease: false
            draft: false
            files: |
              proot
            repo_token: ${{ secrets.GITHUB_TOKEN }}
